#!/bin/sh
#Makes a preinstall script for a Composer package. I install my science apps into a folder "/Applications/Scientific Applications." This will generate a script that will delete an existing folder of that name before the install.
#This script runs directly on the sources in the finder the JAMF Composer uses.

SCRIPTTOMAKE=preinstall

#Provide the name of the Composer package location to generate a script for

if [ -n "$1" ]
then
    PATHTOPKG="$1"
else
    echo 'Argument missing: Enter the path to the Composer installer source to edit here (hint: try /Library/Application Support/JAMF/Composer/Sources/<source name>)'
    exit 1
fi

#Check that the composer source folder exists
if [ ! -d "$1" ]
then
    echo Source directory not found
    exit 1
fi

#Check if a script already exists
if [ -f "$1/Scripts/$SCRIPTTOMAKE" ]
then
    echo `basename "$1"` "already has a \"$SCRIPTTOMAKE\" script."
    echo "Overwrite that file? (yes/no)"
    read OVERWRITE
    if [ ! $OVERWRITE = "yes" ]
    then
        exit 1
    fi
fi



TODEL=`find "$1/ROOT/Applications/Scientific Applications"  -type d -depth 1`

if [ -z "$TODEL" ]
then
    echo no directories found in "$1/ROOT/Applications/Scientific Applications"
    exit 1
fi

TODEL=$(basename "$TODEL")


#
# create script
#

cat > "$1/Scripts/$SCRIPTTOMAKE"<< EOF
#!/bin/sh
## preinstall

pathToScript=\$0
pathToPackage=\$1
targetLocation=\$2
targetVolume=\$3

#Delete old version of folder in Scientific Applications if present

BASEDIR="/Applications/Scientific Applications"
PROGRAMDIR="$TODEL"
[ -d "\$BASEDIR/\$PROGRAMDIR" ] && rm -rf "\$BASEDIR/\$PROGRAMDIR"

exit 0		## Success
exit 1		## Failure
EOF



chmod a+x "$1/Scripts/$SCRIPTTOMAKE"

exit 0