#!/bin/sh
#Prep Composer sources prior to building using the Composer application
# -Remove "Downloaded from internet warnings"
# -Change owner
# -Change informatoin plists to source folder name
#  NOTE- this assumes that the version number is after the last - in the file name


#Provide the name of the Composer package location to perform actions on

if [ -n "$1" ]
then
    PATHTOPKG="$1"
else
    echo 'Argument missing: Enter the path to the Composer installer source to edit here (hint: try /Library/Application Support/JAMF/Composer/Sources/<source name>)'
    exit 1
fi

#Check that the composer source folder exists
if [ ! -d "$1" ]
then
    echo Source directory not found
    exit 1
fi


#
# Remove "Downloaded from internet warnings" and change owner to root:admin
#

#Check that the composer source folder exists
if [ ! -d "$1/ROOT" ]
then
    echo Source directory is missing ROOT folder
    exit 1
fi

chown -R root:admin "$1/ROOT"
xattr -d -r com.apple.quarantine "$1/ROOT"

#
# Use the folder name to change the information plists
#

NAME=$(basename "$1")
NAMENOSPACES=`echo $NAME | sed 's/ //g'`
VERSION=`echo $NAMENOSPACES | sed 's/.*-\(.*\)/\1/'`

defaults write "$1/Settings/English.lproj/Description.plist" IFPkgDescriptionDescription -string "The program: $NAME"
defaults write "$1/Settings/English.lproj/Description.plist" IFPkgDescriptionTitle -string "$NAMENOSPACES"
defaults write "$1/Settings/Info.plist" CFBundleGetInfoString -string "$NAMENOSPACES"
defaults write "$1/Settings/Info.plist" CFBundleIdentifier -string "$NAMENOSPACES"
defaults write "$1/Settings/Info.plist" CFBundleShortVersionString -string "$VERSION"
